# Generated by Django 2.1.1 on 2019-01-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='reg_time',
            field=models.DateField(),
        ),
    ]
