# Generated by Django 2.1.1 on 2019-01-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_auto_20190114_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='music_url',
            field=models.URLField(default=''),
        ),
    ]
