# Generated by Django 2.1.1 on 2019-01-15 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0003_song_music_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='users',
            field=models.ManyToManyField(blank=True, to='Server.AppUser'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='Server.Song'),
        ),
    ]
