# Generated by Django 2.1.1 on 2019-01-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0005_remove_appuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='user_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
