# Generated by Django 2.1.1 on 2019-01-16 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0006_appuser_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_builder', models.BooleanField(default=False)),
                ('appuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.AppUser')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='album_year',
            field=models.IntegerField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='build_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='user',
            field=models.ManyToManyField(through='Server.UserList', to='Server.AppUser'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Server.PlayList'),
        ),
    ]
