# Generated by Django 2.1.1 on 2019-01-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0007_auto_20190116_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_year',
            field=models.IntegerField(),
        ),
    ]
