# Generated by Django 2.1.1 on 2019-01-16 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0009_auto_20190116_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='appuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Server.AppUser'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='playlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Server.PlayList'),
        ),
    ]
