# Generated by Django 2.1.1 on 2019-01-17 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0011_auto_20190117_0030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='build_user',
        ),
    ]
