# Generated by Django 2.1.1 on 2019-01-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0012_remove_playlist_build_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='build_user',
            field=models.ForeignKey(default=1, on_delete=True, related_name='build_user', to='Server.AppUser'),
        ),
    ]
