# Generated by Django 2.1.1 on 2019-01-17 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0014_remove_playlist_build_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='build_date',
        ),
    ]
