# Generated by Django 2.1.1 on 2019-01-17 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0015_remove_playlist_build_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='build_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='playlist',
            name='build_user',
            field=models.ForeignKey(default=1, on_delete=True, related_name='build_user', to='Server.AppUser'),
        ),
    ]
